import { Metadata } from "next";
import "@/assets/css/globals.css";
import { http } from "@/lib/http";
import { hasLocale } from "next-intl";
import { User } from "@/types/global";
import { cookies } from "next/headers";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import { NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { UserProvider } from "@/providers/user-data";
import { DirectionProvider } from "@/components/ui/direction";
import { Inter, Playfair_Display, Cairo } from "next/font/google";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dallal",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  let user: User | null = null;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const dir = locale === "ar" ? "rtl" : "ltr";

  if (token) {
    const { data, ok } = await http.get<{
      data: User;
    }>("/api/v1/auth/me");

    if (!ok) {
      throw new Error("Failed to fetch user data");
    }

    user = data.data;
  }

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${inter.variable} ${playfair.variable} ${cairo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider initialUser={user}>
          <NuqsAdapter>
            <NextIntlClientProvider>
              <DirectionProvider dir={dir}>
                <main>{children}</main>
                <Toaster richColors position="top-right" />
              </DirectionProvider>
            </NextIntlClientProvider>
          </NuqsAdapter>
        </UserProvider>
      </body>
    </html>
  );
}
